- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: coreutils }
      - { name: zsh, install_options: disable-etcdir }
      - { name: wget }
      - { name: curl }
      - { name: pkg-config }
      - { name: tree }
      - { name: nkf }
      - { name: jq }
      - { name: go }
      - { name: direnv }
      - { name: peco }
      - { name: hub }
      - { name: tig }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: lha }
      - { name: sqlite }
      - { name: redis }
      - { name: imagemagick }
      - { name: xz }
      - { name: socat }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: phantomjs }
      - { name: source-highlight }
      # - { name: git }
      # - { name: mysql }
    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: skype }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: java }
      - { name: sourcetree }
      - { name: karabiner }
      - { name: flux }
      - { name: dash }
      - { name: atom }
      - { name: vagrant }
      - { name: virtualbox }
      # - { name: kobito }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{ homebrew_packages }}"
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

    # cask
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: "{{ homebrew_cask_packages }}"
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: "{{ cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

    - name: xquartz のインストール
      homebrew_cask: name=xquartz

    - name: install anyenv
      git: repo=git@github.com:riywo/anyenv.git dest=~/.anyenv version=master accept_hostkey=yes

    - name: isntall zprezto
      git: repo=git@github.com:sorin-ionescu/prezto.git dest=~/.zprezto version=master accept_hostkey=yes
